### ISSUE TITLE
Endpoint request timed out

### ISSUE THREAD

**Issue by pradeeptk304** [tsedio/tsed-example-aws#3]
I checked out the project and had to change runtime to nodejs12.x in order to deploy to AWS. Even though the request was processed successfully the response from Lambda never reached API Gateway so the request timeout and after that the lambda also timed out. I have attached the logs.

Could someone help me please?

Thanks,
Pradeep
[api_gateway_logs.txt](https://github.com/TypedProject/tsed-example-aws/files/4659333/api_gateway_logs.txt)
[lambda_logs.txt](https://github.com/TypedProject/tsed-example-aws/files/4659334/lambda_logs.txt)

**Comment by pradeeptk304** [comment]
I was able to fix the issue by updating LambdaServer.ts to return the promise.

return awsServerlessExpress.proxy(lambdaServer, event, context, 'PROMISE').promise;

instead of 

awsServerlessExpress.proxy(lambdaServer, event, context);
done();

**Comment by Romakita** [comment]
Ha ok the returned valud is missing :). I'll fix that :)
